# .github/workflows/release.yml
name: Release Workflow

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15.8"

      - name: Build and publish
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
          # 以下の環境変数はデフォルトで利用可能ですが、明示的に指定することもできます。
          # GITHUB_REF: ${{ github.ref }}
        run: |
          echo "Running build and publish commands"
          # ここにビルドと公開に関するコマンドを記述します。
          # 例えば、GoReleaserを使ってリリースを自動化することができます。
